### ISSUE TITLE
Unique dataset value not working

### ISSUE THREAD

**Issue by Vikash-tig** [rollno748/Extended-csv-dataset-config#12]
The other combinations are working fine except for this one, I am not sure if I am doing anything wrong.
When I was trying to select the unique row on each iteration/once the jmeter is throwing below error:

2023-03-13 16:17:55,943 ERROR o.a.j.t.JMeterThread: Test failed!
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:675) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
	at com.di.jmeter.config.ExtendedCsvDataSetConfig.initBlockFeatures(ExtendedCsvDataSetConfig.java:164) ~[di-extended-csv-2.0.jar:?]
	at com.di.jmeter.config.ExtendedCsvDataSetConfig.initVars(ExtendedCsvDataSetConfig.java:152) ~[di-extended-csv-2.0.jar:?]
	at com.di.jmeter.config.ExtendedCsvDataSetConfig.iterationStart(ExtendedCsvDataSetConfig.java:53) ~[di-extended-csv-2.0.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:160) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.TransactionController.nextWithoutTransactionSampler(TransactionController.java:205) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.TransactionController.next(TransactionController.java:135) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.GenericController.nextIsAController(GenericController.java:222) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:175) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:134) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:99) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:266) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

![image](https://user-images.githubusercontent.com/34403141/224681592-a6d9b7bd-dbef-49b8-96fa-389e50390c51.png)

**Comment by rollno748** [comment]
I have updated the code for gui as well - It should select the autoallocate by default (if not set) when unique selection is enabled

Can you try uninstalling the plugin and install it again ?

**Comment by Vikash-tig** [comment]
> Hello Vikash
> 
> Thanks for bringing up - From the screenshot you have shared I could see the Allocate block is unset
> 
> Try setting the value to Autoallocate or custom allocate and give it a try

I tried autoallocating the value and still it is throwing some error:
![image](https://user-images.githubusercontent.com/34403141/224689476-5d788a11-58ef-4e35-882f-3bf0f9b951a9.png)

**Comment by Vikash-tig** [comment]
> I have updated the code for gui as well - It should select the autoallocate by default (if not set) when unique selection is enabled
> 
> Can you try uninstalling the plugin and install it again ?

I will try this method.

**Comment by rollno748** [comment]
I tried the same - it works fine with me

![image](https://user-images.githubusercontent.com/18440913/224692838-9b540efa-64eb-475c-a425-4e00a28d6897.png)
![image](https://user-images.githubusercontent.com/18440913/224692874-3931b4d4-5331-466b-8b6b-7605a126531f.png)


Couple of things:
1. Check your csv file path 
2. Check your csv file by clicking Edit button 
3. Check your delimiter value

**Comment by rollno748** [comment]
Hi,

Did you get a chance to check the issue?

**Comment by Vikash-tig** [comment]
Thanks, 
After building the jar again it was running fine.

**Comment by rollno748** [comment]
FYI: It's already available with plugins manager.
I will mark this issue as closed

Feel free to hit a star, it means a lot
