### ISSUE TITLE
不支持参数化文件相对路劲

### ISSUE THREAD

**Issue by zhangzhaox** [rollno748/Extended-csv-dataset-config#2]
![image](https://user-images.githubusercontent.com/82088551/164887803-6f2cde71-2f28-4693-b7f8-16c89d59b9b4.png)
![image](https://user-images.githubusercontent.com/82088551/164887844-a1db7eaa-1187-4ec8-a510-cc323fef7961.png)

**Comment by rollno748** [comment]
Thanks for opening the issue,

I don't think you have placed the csv/txt file properly. When you don't provide the path for the csv/txt - The JMeter will try to find it in the same place where you have kept the jmx file. 

I have tried the same option as yours - It works fine perfectly for me 

![image](https://user-images.githubusercontent.com/18440913/164889299-6137b097-dfe2-4006-9d9d-6f11e5e02d71.png)

![image](https://user-images.githubusercontent.com/18440913/164889337-bb2338a6-3220-4ee1-8faf-7de9fdba19a1.png)

**Comment by zhangzhaox** [comment]
2022-04-25 15:13:34,898 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2022-04-25 15:13:34,899 INFO o.a.j.t.JMeterThread: Thread started: 线程组 1-1
2022-04-25 15:13:34,899 INFO c.d.j.u.ExtFileServer: Stored: 10w_vin.txt Alias: 10w_vin.txt@1413763366**
2022-04-25 15:13:34,900 ERROR o.a.j.t.JMeterThread: Test failed!
java.lang.IllegalArgumentException: File 10w_vin.txt must exist and be readable
	at com.di.jmeter.utils.ExtFileServer.createBufferedReader(ExtFileServer.java:433) ~[di-extended-csv-1.1.jar:?]
	at com.di.jmeter.utils.ExtFileServer.readLine(ExtFileServer.java:346) ~[di-extended-csv-1.1.j
[10w_vin.txt](https://github.com/rollno748/Extended-csv-dataset-config/files/8552398/10w_vin.txt)
ar:?]
	at com.di.jmeter.utils.ExtFileServer.readSequential(ExtFileServer.java:599) ~[di-extended-csv-1.1.jar:?]
	at com.di.jmeter.config.ExtendedCsvDataSet.iterationStart(ExtendedCsvDataSet.java:89) ~[di-extended-csv-1.1.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) ~[ApacheJMeter_core.ja


[Extended-csv-dataset-config.zip](https://github.com/rollno748/Extended-csv-dataset-config/files/8552404/Extended-csv-dataset-config.zip)

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/165042130-e5b40c31-4a20-4755-8cdc-50b150099af3.png)
