### ISSUE TITLE
Does not work in Distributed testing 

### ISSUE THREAD

**Issue by binayaparhy** [rollno748/Extended-csv-dataset-config#22]
Below is the error. 

2024-03-27 16:21:20,181 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2024-03-27 16:21:20,182 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2024-03-27 16:21:20,332 INFO o.a.j.r.ClassFinder: Will scan jar C:\FTP_Jmter_LoadTest\apache-jmeter-5.6.3\apache-jmeter-5.6.3\lib\ext\di-extended-csv-2.2.jar with filter ExtendsClassFilter [parents=[interface org.apache.jmeter.functions.Function], inner=false, contains=null, notContains=null]. Consider exposing JMeter plugins via META-INF/services, and add JMeter-Skip-Class-Scanning=true manifest attribute so JMeter can skip classfile scanning
2024-03-27 16:21:20,340 INFO o.a.j.r.ClassFinder: Will scan jar C:\FTP_Jmter_LoadTest\apache-jmeter-5.6.3\apache-jmeter-5.6.3\lib\ext\jmeter-plugins-manager-1.10.jar with filter ExtendsClassFilter [parents=[interface org.apache.jmeter.functions.Function], inner=false, contains=null, notContains=null]. Consider exposing JMeter plugins via META-INF/services, and add JMeter-Skip-Class-Scanning=true manifest attribute so JMeter can skip classfile scanning
2024-03-27 16:21:20,769 INFO c.d.j.u.FileServerExtended: Default base='C:\FTP_Jmter_LoadTest\apache-jmeter-5.6.3\apache-jmeter-5.6.3\bin'
**2024-03-27 16:21:20,770 ERROR o.a.j.e.StandardJMeterEngine: Unable to execute testStarted(FTDC6LRU002) for test element com.di.jmeter.config.ExtendedCsvDataSetConfig@f0cd55a5
java.lang.NullPointerException: Cannot invoke "org.apache.jmeter.gui.GuiPackage.getTestPlanFile()" because the return value of "org.apache.jmeter.gui.GuiPackage.getInstance()" is null**
	at com.di.jmeter.config.ExtendedCsvDataSetConfig.testStarted(ExtendedCsvDataSetConfig.java:210) ~[di-extended-csv-2.2.jar:?]
	at com.di.jmeter.config.ExtendedCsvDataSetConfig.testStarted(ExtendedCsvDataSetConfig.java:227) ~[di-extended-csv-2.2.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:249) ~[ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:432) ~[ApacheJMeter_core.jar:5.6.3]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by binayaparhy** [comment]
Jmeter version 5.6.3, java 21.0.2 2024-01-16 LTS, di-extended-csv-2.2.jar:

**Comment by rollno748** [comment]
Hello @binayaparhy 
Thanks for reporting this. Can you please provide your complete jmeter.log file from the master and slave ?

**Comment by binayaparhy** [comment]
[jmeter - Copy.log](https://github.com/rollno748/Extended-csv-dataset-config/files/14850106/jmeter.-.Copy.log)
[jmeter-server - Copy.log](https://github.com/rollno748/Extended-csv-dataset-config/files/14850107/jmeter-server.-.Copy.log)

**Comment by binayaparhy** [comment]
Can you confirm that you have the plugin installed on your slaves as well (should be of same version) ? Yes, same version installed using Plugin manager in Slave
Can you please provide your complete jmeter.log file from the master and slave ? - Attached with sanitised server name and IP

**Comment by binayaparhy** [comment]
Hi, is there any update on this issue please? I am trying to use this new data set config for one of my test.

**Comment by rollno748** [comment]
Hey @binayaparhy 

I have been keeping busy lately. Will push an update to the plugins soon 

Thanks

**Comment by rollno748** [comment]
Can you validate this please ?

https://github.com/rollno748/Extended-csv-dataset-config/releases/download/untagged-d002a8f5b422693e1c27/di-extended-csv-2.3.jar

and let meknow, if the issue still persist

**Comment by binayaparhy** [comment]
The link is not opening

**Comment by rollno748** [comment]
Can you try with the below link 
https://github.com/rollno748/Extended-csv-dataset-config/releases/download/2.3/di-extended-csv-2.3.jar

**Comment by binayaparhy** [comment]
I am not able to download the Jar, were you able to reproduce the issue? if it the fix works fine, you can publish it to the plugin manager where I can take it.

**Comment by rollno748** [comment]
I dont have an env to test it

**Comment by binayaparhy** [comment]
Our organisation has blocked download of jar files

**Comment by rollno748** [comment]
Only option I see is by compiling the jar by yourself or raise an IT ticket and get it downloaded

**Comment by binayaparhy** [comment]
Hello, I have been able to download from a different machine and tested it works in distributed mode. Please let me know once it is published

**Comment by rollno748** [comment]
Hey @binayaparhy 

I have merged the changes and released the 2.3 version to plugins manager.
Thanks for supporting and please feel free to raise a issue if you find any abnormalities / any idea / new feature to be added to this 

**Please hit a star, if you like our contribution to opensource**

**Comment by binayaparhy** [comment]
Hi Mohamed,

Thanks for your help. I have a feature in mind but not sure it will be
fesible in Jmeter architecture.

Its one feature about test data management that other commercial tools like
Loadeunner and Neoload provide but jmeter does not as per my understanding.

The capability is : splitting the csv data set from the controller into as
many files as the number of agents and then transfering them to the
corresponding storage of the host. This ensure uniqeness of test data
across the Test and also ensure tester do not have to do this task manually.

Thanks. Happy to provide any more requirement if needed.

Regards
Binaya

**Comment by rollno748** [comment]
@binayaparhy 
The splitting of the csv feature is a part from the jmeter core engine rather than a plugin by itself. 

But I will have it a thinking on that feature.

Thanks for the input though.
